### ISSUE TITLE
History size K

### ISSUE THREAD

**Issue by tvogels** [windows7lover/RegularizedNonlinearAcceleration#3]
Thanks for sharing this code! I was looking into it, and am a bit confused by this line:

https://github.com/windows7lover/RegularizedNonlinearAcceleration/blob/3a56775a42116ca11eb222cef4c4aae7dd0242fe/Python/Modules/AccelerationModule.py#L66

Is the `K+1` correct? I imagine the length of x_hist should be at most K+1, and it seems that with this test, the size of x_hist grows to K+2, resulting in weight vectors of length K+1.

**Comment by yunmingxiao** [comment]
Same issue with tvogels

**Comment by windows7lover** [comment]
Indeed, it should be ">=". Thank you !
